# Generated by Django 4.1.5 on 2023-01-28 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('littlelemon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='inventory',
            new_name='stock',
        ),
    ]
