# Generated by Django 4.1.5 on 2023-01-28 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('littlelemon', '0003_category_menuitem_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='Category',
            new_name='category',
        ),
    ]
