# Generated by Django 4.1.6 on 2023-02-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littlelemon', '0004_alter_cart_unique_together_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='menuitem',
        ),
        migrations.AddField(
            model_name='cart',
            name='menuitem',
            field=models.ManyToManyField(to='littlelemon.menuitem'),
        ),
    ]
