# Generated by Django 4.1.5 on 2023-01-30 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('littlelemon', '0006_rename_stock_menuitem_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
    ]
