# Generated by Django 4.1.6 on 2023-02-05 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('littlelemon', '0010_cart_cart_item_alter_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_item',
        ),
        migrations.AddField(
            model_name='cart',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item', to='littlelemon.cartitem'),
        ),
        migrations.RemoveField(
            model_name='cart',
            name='cartitem',
        ),
        migrations.AddField(
            model_name='cart',
            name='cartitem',
            field=models.ManyToManyField(to='littlelemon.cartitem'),
        ),
    ]
