# Generated by Django 4.1.6 on 2023-02-05 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('littlelemon', '0011_remove_cart_cart_item_cart_item_remove_cart_cartitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='item',
        ),
    ]
