# Generated by Django 4.1.6 on 2023-02-05 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('littlelemon', '0012_remove_cart_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cartitem',
            new_name='cartitems',
        ),
    ]
