# Generated by Django 4.1.6 on 2023-02-06 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('littlelemon', '0014_alter_orderitem_unique_together_orderitem_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cartitem',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='littlelemon.cartitem'),
        ),
    ]
