# Generated by Django 4.1.6 on 2023-02-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littlelemon', '0018_rename_status_order_delivered_remove_order_cartitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.RemoveField(
            model_name='purchases',
            name='orderitem',
        ),
        migrations.AddField(
            model_name='purchases',
            name='orderitem',
            field=models.ManyToManyField(to='littlelemon.orderitem'),
        ),
    ]
