# Generated by Django 4.1.6 on 2023-02-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littlelemon', '0019_purchases_date_remove_purchases_orderitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
