# Generated by Django 4.1.6 on 2023-02-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littlelemon', '0023_rename_purchases_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='added_on',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='cartitems',
        ),
        migrations.AddField(
            model_name='cart',
            name='orderitems',
            field=models.ManyToManyField(to='littlelemon.orderitem'),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
