# Generated by Django 4.1.6 on 2023-02-06 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('littlelemon', '0024_remove_cart_added_on_remove_cart_cartitems_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='orderitem',
            new_name='orderitems',
        ),
    ]
